import { Inter } from 'next/font/google'
import './globals.css'
import NavBar from './components/nav-bar';
import Footer from './components/footer';
import {Providers} from "./providers";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Camping nettside',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Providers>
        <NavBar />
        <div>{children}</div>
         <Footer />
        </Providers>
      </body>
      
     
    </html>
  );
}
