import { Inter } from 'next/font/google'
import './globals.css'
import NavBar from './components/nav-bar';
import Footer from './components/footer';
import { ClerkProvider } from '@clerk/nextjs'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Camping nettside',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body className={inter.className}>
        <NavBar />
        <div>{children}</div>
      </body>
      <Footer />
    </html>
    </ClerkProvider>
  );
}
