
import './globals.css';
import NavBar from '../components/nav-bar';
import Footer from '../components/footer';
import {Providers} from "./nextUIprovider";
import initTranslations from '../i18n';
import TranslationsProvider from '../components/TranslationsProvider';
import { getServerSession } from 'next-auth';
import SessionProvider from '../utils/SessionProvider'

const i18nNamespaces = ['Common', 'Home'];

export const metadata = {
  title: 'Camping nettside',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children, params: { locale } }) {
 
  const { resources, t } = await initTranslations(locale, i18nNamespaces);

  const session = await getServerSession();
  return (
    <html lang={locale}>
      <body>
        <SessionProvider>
          <TranslationsProvider resources={resources} locale={locale} namespaces={i18nNamespaces}>
            <NavBar />
            <main>{children}</main>
            <Footer />
          </TranslationsProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
  
  
  
