/*Skrevet av Jesper*/

import './globals.css';
import NavBar from '../components/nav-bar';
import Footer from '../components/footer';

import initTranslations from '../i18n';
import TranslationsProvider from '../components/TranslationsProvider';
import SessionProvider from '../utils/SessionProvider'

const i18nNamespaces = ['Common', 'Home']; // bestemmer hvilke namespaces som skal bli brukt fra i18nexus for denne filen

export const metadata = {
  title: 'Camping nettside',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children, params: { locale } }) {
 
  try {
  const { resources, t } = await initTranslations(locale, i18nNamespaces);

  return (
    <html lang={locale}>
      <body>
        <SessionProvider>
          <TranslationsProvider resources={resources} locale={locale} namespaces={i18nNamespaces}>
            <NavBar />
            <main>{children}</main>
            <Footer />
          </TranslationsProvider>
        </SessionProvider>
      </body>
    </html>
  );
} catch (error) {
  console.error('Error initializing translations:', error);
  
  return <div>Error initializing translations. Please try again later.</div>;
}
}
  
  
  
